# Generated by Django 6.0.3 on 2026-04-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terrain',
            name='images',
            field=models.ManyToManyField(blank=True, to='terrains.terrainimage'),
        ),
    ]
