# Generated by Django 6.0.3 on 2026-04-08 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='player_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
