# Generated by Django 6.0.3 on 2026-04-06 14:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_reservations', models.IntegerField(default=10)),
                ('can_create_tournament', models.BooleanField(default=False)),
                ('can_manage_terrain', models.BooleanField(default=False)),
            ],
        ),
    ]
