# Generated by Django 6.0.3 on 2026-04-06 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terrains', '0002_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captain_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='terrain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='terrains.terrain'),
        ),
    ]
