# Generated by Django 6.0.3 on 2026-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_joinrequest_tournamentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
