# Generated by Django 6.0.3 on 2026-04-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_tournament_type_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='phase',
            field=models.CharField(choices=[('group', 'Phase de Poules'), ('round_of_16', 'Huitièmes de finale'), ('quarter', 'Quarts de finale'), ('semi', 'Demi-finales'), ('third_place', 'Match pour la 3ème place'), ('final', 'Finale')], default='group', max_length=20),
        ),
    ]
