# Generated by Django 6.0.3 on 2026-04-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_match_group_name_match_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
