# Generated by Django 6.0.3 on 2026-04-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
